client_config_backend: file
client_config_file: client_secret.json

oauth_scope:
  - https://www.googleapis.com/auth/drive

save_credentials: true
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: true
